spring:
  datasource:
    url: ${DB_URL_PG}
    username: ${DB_USERNAME_PG}
    password: ${DB_PASSWORD_PG}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  security:
    cors:
      dev: false # Activa CORS restringido para React / producción